name: test-build

on:
  - push

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        version: [latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - uses: xmake-io/github-action-setup-xmake@master
        with:
          xmake-version: ${{ matrix.version }}
      - name: Build project
        run: |
          xmake --version
          xmake build -y
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: |
            build
            !build/.deps
            !build/.objs